#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export WEBKIT_EXEC_PATH="$HERE/usr/lib/webkit2gtk-4.1"
export LD_LIBRARY_PATH="$HERE/usr/lib:$HERE/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:-}"
export WEBKIT_DISABLE_DMABUF_RENDERER="${WEBKIT_DISABLE_DMABUF_RENDERER:-1}"
export WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS="${WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS:-1}"
exec "$HERE/usr/bin/quotadeck-desktop" "$@"
